BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 9e-4
  MODEL_FILE_NAME: AriaPPG_AriaPPG_ibvpnet
  PLOT_LOSSES_AND_LR: True
  DATA:
    FILTERING:
      SELECT_TASKS: True
      TASK_LIST: 
        - T1
      SELECT_CAM: True
      CAM_LIST: 
        - stat
    FS: 30
    DATASET: AriaPPG
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/raw"                     # DiffNormalized dataset path, need to be updated
    CACHED_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/prep"
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.65
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']         #if use physnet, should be DiffNormalized
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: False
      RESIZE:
        H: 128
        W: 128
VALID:
  DATA:
    FILTERING:
      SELECT_TASKS: True
      TASK_LIST: 
        - T1
      SELECT_CAM: True
      CAM_LIST: 
        - stat
    FS: 30
    DATASET: AriaPPG
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/raw"                     # DiffNormalized dataset path, need to be updated
    CACHED_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/prep"
    EXP_DATA_NAME: ""
    BEGIN: 0.65
    END: 0.85
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']         #if use physnet, should be DiffNormalized
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: False
      RESIZE:
        H: 128
        W: 128
TEST:
  METRICS: ['MAE']
  USE_LAST_EPOCH: False                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: AriaPPG
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/raw"                     # DiffNormalized dataset path, need to be updated
    CACHED_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/prep"
    EXP_DATA_NAME: ""
    BEGIN: 0.85
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']         #if use physnet, should be DiffNormalized
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: False
      RESIZE:
        H: 128
        W: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/train_configs/iBVPNet/median/diffnormalized/pxt1stat
MODEL:
  DROP_RATE: 0.2
  NAME: iBVPNet
  iBVPNET:
    FRAME_NUM: 128
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: ["peak detection", "FFT"]        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: ""