BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 15
  LR: 9e-4
  MODEL_FILE_NAME: AriaPPG_AriaPPG_arianet
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: AriaPPG
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/raw"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/prep"
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.65
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: False
      RESIZE:
        H: 128
        W: 128
VALID:
  DATA:
    FS: 30
    DATASET: AriaPPG
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/raw"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/prep"
    EXP_DATA_NAME: ""
    BEGIN: 0.65
    END: 0.85
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: False
      RESIZE:
        H: 128
        W: 128
TEST:
  METRICS: ['MAE']
  USE_LAST_EPOCH: False                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: AriaPPG
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/raw"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/prep"
    EXP_DATA_NAME: ""
    BEGIN: 0.85
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: False
      RESIZE:
        H: 128
        W: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: /cluster/scratch/boehis/runs/train_configs/PhysNet/median/multimodal/conv_modulation_2-4-8-10_quaternion
MODEL:
  DROP_RATE: 0.2
  NAME: AriaNet
  ARIANET:
    FRAME_NUM: 128
    LOSS_TRAIN: 'soft_macc'
    LOSS_VAL: 'soft_macc'
    INTEGRATION_STRATEGY: 'conv_modulation'
    INTEGRATION_LAYERS: [2, 4, 8, 10]
    SENSOR_TYPE: 'quaternion'
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: ["peak detection", "FFT"]        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: ""
