BASE: ['']
TOOLBOX_MODE: "unsupervised_method"      # "train_and_test"  or "only_test" or "unsupervised_method"
UNSUPERVISED:
  METHOD: ["ICA", "POS", "CHROM", "GREEN", "LGI"]
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA', 'MACC']
  DATA:
    FS: 30
    DATASET: AriaPPG
    DO_PREPROCESS: True                # if first time, should be true
    DATA_FORMAT: NDHWC
    DATA_PATH: "/cluster/scratch/boehis/preprocessed/none/len128/raw"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/cluster/scratch/boehis/preprocessed/none/len128/prep"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Raw
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: False
      RESIZE:
        H: 128
        W: 128
INFERENCE:
  EVALUATION_METHOD: ["peak detection", "FFT"]        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
LOG:
  PATH: 'runs/infer_configs/UNSUPERVISED/none/len128/res128/'
