BASE: ['']
TOOLBOX_MODE: "loso_cv"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 15
  LR: 9e-4
  MODEL_FILE_NAME: AriaPPG_AriaPPG_physnet
  PLOT_LOSSES_AND_LR: True
  DATA:
    LOSO_SUBJECTS: ['P001', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008', 'P009', 'P010', 'P011', 'P012', 'P014', 'P015', 'P016', 'P017', 'P018', 'P019', 'P020', 'P021', 'P023','P024']    
    FS: 30
    DATASET: AriaPPG
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/raw"                     # DiffNormalized dataset path, need to be updated
    CACHED_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/prep"
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: False
      RESIZE:
        H: 128
        W: 128
TEST:
  METRICS: ['MAE']
  USE_LAST_EPOCH: False                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: AriaPPG
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/raw"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/cluster/scratch/boehis/preprocessed/median/len128/prep"
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']         #if use physnet, should be DiffNormalized
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: False
      RESIZE:
        H: 128
        W: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: /cluster/scratch/boehis/runs/train_configs/PhysNet/median/loss_function_comparison/loso_mcc
MODEL:
  DROP_RATE: 0.2
  NAME: Physnet
  PHYSNET:
    FRAME_NUM: 128
    LOSS_TRAIN: 'mcc'
    LOSS_VAL: 'mcc'
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: ["peak detection", "FFT"]        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: ""